"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {IndianRupee,Receipt,Users,TrendingUp,PlusCircle} from "lucide-react";
import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid} from "recharts";
import SummaryCard from "../components/SummaryCard";
import {getPeople,getExpenses,totals} from "../lib/storage";
import {money,dateLabel} from "../lib/utils";
export default function Dashboard(){const[d,setD]=useState(null);useEffect(()=>{const load=()=>setD({...totals(getPeople(),getExpenses()),recentExpenses:getExpenses().slice(0,8)});load();addEventListener("storage",load);return()=>removeEventListener("storage",load)},[]);if(!d)return <div>Loading...</div>;return <div className="space-y-7">
<div className="flex flex-col sm:flex-row sm:justify-between gap-4"><div><h1 className="text-3xl font-bold">Dashboard</h1><p className="text-slate-500 mt-1">Track every marriage expense in one place.</p></div><Link href="/expenses/add" className="bg-rose-600 text-white px-4 py-3 rounded-xl font-semibold inline-flex items-center gap-2"><PlusCircle size={18}/>Add Expense</Link></div>
<div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4"><SummaryCard title="Total Expenditure" value={money(d.totalExpenditure)} Icon={IndianRupee}/><SummaryCard title="Total Expenses" value={d.totalExpenses} Icon={Receipt}/><SummaryCard title="Total People" value={d.totalPeople} Icon={Users}/><SummaryCard title="Highest Expense" value={money(d.highestExpense?.amount)} Icon={TrendingUp} sub={d.highestExpense?.title||"No expenses"}/></div>
<div className="grid xl:grid-cols-2 gap-6"><section className="bg-white border rounded-2xl p-5"><h2 className="font-bold text-lg mb-4">Person-wise Expenditure</h2>{d.personWise.map(p=><Link key={p.id} href={`/people/${p.id}`} className="flex justify-between p-3 rounded-xl hover:bg-slate-50"><span><b>{p.name}</b><small className="text-slate-500 ml-2">{p.expenses} expenses</small></span><b>{money(p.total)}</b></Link>)}</section><section className="bg-white border rounded-2xl p-5"><h2 className="font-bold text-lg mb-4">Category-wise Expenditure</h2><div className="h-64"><ResponsiveContainer><BarChart data={d.categoryWise}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="_id" tick={{fontSize:10}}/><YAxis/><Tooltip formatter={v=>money(v)}/><Bar dataKey="total" fill="#e11d48" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></section></div>
<section className="bg-white border rounded-2xl p-5"><div className="flex justify-between mb-4"><h2 className="font-bold text-lg">Recent Expenses</h2><Link href="/expenses" className="text-rose-600 font-semibold">View All</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead><tr className="text-left text-slate-500 border-b">{["Person","Expense","Category","Amount","Date"].map(x=><th key={x} className="py-3">{x}</th>)}</tr></thead><tbody>{d.recentExpenses.map(e=><tr key={e.id} className="border-b last:border-0"><td className="py-3">{e.personName}</td><td>{e.title}</td><td>{e.category}</td><td className="font-semibold">{money(e.amount)}</td><td>{dateLabel(e.date)}</td></tr>)}</tbody></table></div></section>
</div>}
